### ISSUE TITLE
Multiple attributes set for main lib are trashed during repack

### ISSUE THREAD

**Issue by RomainHautefeuille** [gluck/il-repack#133]
For instance if you set twice InternalsVisibleTo for the main assembly, only one will be kept by ILRepack. I know there is an option to allow multiple attributes, but I think the option is meant to allow multiple attributes coming from merged libs. In my case, the attributes were already set multiple times in the main assembly, so it seems wrong for ILRepack to keep only one.

**Comment by RomainHautefeuille** [comment]
Well, I took a look at the code, and I have a better understanding of my issue. Actually it is specific to InternalsVisibleTo attribute:
Basically, if you don't sign the assembly at build time and you set an InternalVisibleTo attribute targetting an unsigned lib, if a key is provided while repacking, the attribute is removed.
https://github.com/RomainHautefeuille/il-repack/blob/master/ILRepack/Steps/AttributesRepackStep.cs#L99

I am not sure how I feel about this. In a sense it seems legit to forbid an unsigned lib to access internals from a signed lib, just like at build time. However I am not sure that this is the job of ILRepack to ensure this.

**Comment by gluck** [comment]
as designed then, ILRepack fixes assembly inconsistencies post-merge (you can't have an InternalVisibleTo targeting an unsigned assembly in a signed one)

**Comment by s-krawczyk** [comment]
@gluck The bug is still in actual version. It's not a feature. When you want to repac not signed dll, and it has more than one InternalsVisibleTo set then it leaves only one. This is normal situation when You have dll with test and that dll uses in eg. Moq. Then You need 2 internalsVisibleTo attributes - one for Your test dll and second for Moq DynamicProxy. This has nothing to do with signing dll's in my problem. Any of this dll's are singed.

**Comment by gluck** [comment]
Hi @s-krawczyk,

A signed DLL cannot expose its internals to an unsigned DLL (as per the specs).
> Both the current assembly and the friend assembly must be unsigned, or both assemblies must be signed with a strong name.

(from https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.internalsvisibletoattribute(v=vs.110).aspx)

Hence if you ask ILRepack to build a **signed** DLL, and it finds `InternalsVisibleTo` attributes targetting **unsigned** DLLs, it'll remove them.
But only in that case, and only for the attributes targetting unsigned assemblies, it's not related to the number of such attributes.

This is required to pass the (merged) DLL verification.

Let me know if it helps understanding your issue, or feel free to clarify it.

**Comment by s-krawczyk** [comment]
@gluck Like I wrote before NONE of my assemblies are signed. It still removes internaltsVisibleTo.

**Comment by gluck** [comment]
Feel free to find the issue in the code then, because it should not. Here's the routine removing `InternalsVisibleTo` attributes:
https://github.com/gluck/il-repack/blob/master/ILRepack/Steps/AttributesRepackStep.cs#L99

Note that you still need to pass the options `/copyAttrs` and `/allowMultiple`, maybe that's what you're missing ?

**Comment by s-krawczyk** [comment]
Thank's for note. Added option /allowMultiple and worked.

ps. already cloned repo

Pozdrawiam
SK

2016-08-09 10:51 GMT+02:00 Francois Valdy <notifications@github.com>:
