### ISSUE TITLE
Automatic cleanup of InternalsVisibleTo attributes

### ISSUE THREAD

**Issue by gluck** [gluck/il-repack#45]
When the merged assembly is signed (or delay signed) and includes an unsigned one, there may be InternalsVisibleTo attributes with no PublicKey.

Those will prevent the assembly to properly load, they need to be removed.

**Comment by catester** [comment]
Yes, I agree. I got a report for one assembly bombing out with this error:

> Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.

I don't know what condition changed on the user's machine because previous version of the same assembly repacked with IL-Repack did not cause the error even InternalsVisibleTo attributes were not stripped again back then.

Even if stripping InternalsVisibleTo attributes automatically is not possible, it would be good to have a command line option to remove specific attributes from the output assembly.

**Comment by gluck** [comment]
Fixed by e6c0c2c50103c09494b38af0563bfe91c7313aad and 0b3f5f97bc361b942095d05c02d5d87e5b608f7c
